### ISSUE TITLE
Change code font

### ISSUE THREAD

**Issue by minhduc0711** [Brettm12345/github-moonlight#11]
Great work! 
Is there any way to change the code font to the original mono font used by Github? Thanks.

p/s: sorry this is just a dumb question, I didn't mean to add the bug label

**Comment by aesophor** [comment]
@minhduc0711 

You could change the font by configuring the theme via Stylus, as shown in the following pic:
![scrot-2020-04-01_212133_1680x1050](https://user-images.githubusercontent.com/32998585/78141963-d525e600-745e-11ea-8a40-dc0b92c521ff.png)
