### ISSUE TITLE
Whitespace issue on PR page

### ISSUE THREAD

**Issue by rmountjoy92** [Brettm12345/github-moonlight#14]
**Describe the bug**
code blocks on pull requests are not wrapping properly

**Expected behavior**
all text fits inside text box

**Screenshots**
![image](https://user-images.githubusercontent.com/34513134/78137934-1df48500-73f4-11ea-89ca-a74fb23ed2a9.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Arch linux
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] 80.0.3987.149

**Comment by Brettm12345** [comment]
Please provide a link and I will see

**Comment by rmountjoy92** [comment]
my bad, 
https://github.com/awesome-selfhosted/awesome-selfhosted/pull/2000

**Comment by rmountjoy92** [comment]
This is DOPE btw. I switched to gitea for a while because I hated the Github light theme. There is no going back.
