### ISSUE TITLE
Viewing a repo when not signed in, there's a bar at the top in light mode

### ISSUE THREAD

**Issue by gregk-git** [Brettm12345/github-moonlight#15]
**Describe the bug**
When you are not signed in and you view a repo, there's a large white bar at the top telling you to sign in.

**Expected behavior**
Bar is themed.

**Screenshots**
1. Stylus repo: https://github.com/openstyles/stylus
   * Screenshot: https://i.imgur.com/LDLEwTj.png
2. Dark Reader repo: https://github.com/darkreader/darkreader
   * Screenshot: https://i.imgur.com/0JmYNM0.png

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Version: 81.0.4044.83 (Official Build) beta (64-bit)

**Comment by gregk-git** [comment]
I was also able to reproduce this on Firefox in Ubuntu 18.04
Firefox Version: 74.0 (64-bit)
Screenshot: https://i.imgur.com/xxjXh7C.png

**Comment by Brettm12345** [comment]
I think this has been fixed

**Comment by gregk-git** [comment]
Yes it was, thank you
