### ISSUE TITLE
Stylus symbol counter shows up on non-github domains

### ISSUE THREAD

**Issue by gregk-git** [Brettm12345/github-moonlight#17]
**Describe the bug**
Stylus claims this theme is applying to non-github domains, such as `google.com` but not on all, for example it doesn't show up on `discordapp.com`.

**Expected behavior**
Stylus only claims this is applying the domains it's supposed to.

**Screenshots**
https://i.imgur.com/KvuhmTz.png

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Version: 81.0.4044.83 (Official Build) beta (64-bit)

Note: This may be an issue with stylus, but I was able to reproduce it on Chrome Stable as well, and do not have this issue with other styles.

**Comment by vednoc** [comment]
This is intended behavior in Stylus. [These lines][0] make it so the variables are accessed globally.

To fix this issue, you'd either put them all (or the ones you need) in separate `@-moz-document` blocks, or put them all in a new `@-moz-document` block that has all the domains in it.


[0]: https://github.com/Brettm12345/github-moonlight/blob/0846de1444d84a0e9056392ea7bef5ecced0e982/github.user.css#L70-L115
