### ISSUE TITLE
README Generation

### ISSUE THREAD

**Issue by amayer5125** [Brettm12345/github-moonlight#18]
What is the command you are using to generate the readme.org file? I found `pandoc -t org-smart -f org-smart doc/readme.org -o readme.org` in the *package.json* file, but when I run that command I get very different output than what is in the readme.org file.

I'm using pandoc version 2.9.2.

**Comment by Brettm12345** [comment]
My bad the command is actually `M-x org-org-export-to-org` inside emacs. I haven't figure out how to run that in the shell
