### ISSUE TITLE
[PLUGIN_REQUEST] Octotree

### ISSUE THREAD

**Issue by aasutossh** [Brettm12345/github-moonlight#23]
** URL **
https://addons.mozilla.org/en-US/firefox/addon/octotree/
https://chrome.google.com/webstore/detail/octotree/bkhaagjahfmjljalopjnoealnfndnagc 
Also available for Opera and Safari as well. https://www.octotree.io/download
** Description **
The colors doesn't seem right. I don't mean harm to Octotree's pro plan though. If it's doable please do so, if not Thank you anyway.
Screenshot:
![image](https://user-images.githubusercontent.com/18498932/78207300-00412180-74c1-11ea-9c9d-b0ac611fa778.png)

**Comment by Brettm12345** [comment]
I will get on this. Thank you

**Comment by aasutossh** [comment]
No problem. It's just I like `Octotree` better.
