### ISSUE TITLE
No background color in code suggestion

### ISSUE THREAD

**Issue by minhduc0711** [Brettm12345/github-moonlight#25]
**Describe the bug:**
Currently it's like this:
![image](https://user-images.githubusercontent.com/34294427/78214292-14941700-74df-11ea-9718-497da9b2ebaa.png)

**Expected behavior:**
When it should be something like this:
![image](https://user-images.githubusercontent.com/34294427/78214331-32fa1280-74df-11ea-9c82-211cf7990414.png)

**Comment by Brettm12345** [comment]
Nice find. Could you please provide a link to an example w the issue

**Comment by minhduc0711** [comment]
@Brettm12345 sure, I observe this in every suggestion tho
https://github.com/minhduc0711/graph-theory-usth/pull/1#discussion_r402938512
