### ISSUE TITLE
Can we get a more distinguishing selection color?

### ISSUE THREAD

**Issue by aasutossh** [Brettm12345/github-moonlight#26]
**Describe the bug:**
Hard to see selected (formatted inside of "```")text on page.

**Screenshots:**
First image: 2nd line is selected. First line's `code` is not.
![image](https://user-images.githubusercontent.com/18498932/78222557-28db1280-74e5-11ea-9055-b392f5db0e7d.png)

2nd image: First line's `code` is selected but it's unnoticeable.
![image](https://user-images.githubusercontent.com/18498932/78222676-57f18400-74e5-11ea-812f-76d361a9e290.png)

I don't know if it is a bug or not, or it is intended.

**Comment by Brettm12345** [comment]
Yes. I'll make it blue by default and let the user change it in the settings

**Comment by aasutossh** [comment]
Thank you. You can close this issue.
