### ISSUE TITLE
Typo in repo description

### ISSUE THREAD

**Issue by 3x** [Brettm12345/github-moonlight#3]
It may be small, but I noticed the repo's description text reads `A beatiful dark blue userstyle for GItHub. Made with ❤️` with "GitHub" spelled incorrectly.

Thank you for the beautiful style! <3

**Comment by Brettm12345** [comment]
I can't find the typo in question

**Comment by aesophor** [comment]
@Brettm12345 He probably meant the typo in the repo description. `GItHub` -> `GitHub`
