### ISSUE TITLE
Keywords in code get dark color that merge with dark background

### ISSUE THREAD

**Issue by S3B4S** [Brettm12345/github-moonlight#31]
**Describe the bug:**
In code snippets, some keywords are getting a dark color that merge with the dark background-color, this can be observed in many places.

**Where did this happen:**
Below screenshot can be found at https://github.com/axios/axios/issues/934

**Screenshots:**
<img width="654" alt="image" src="https://user-images.githubusercontent.com/17083334/78356013-11685c00-75af-11ea-8126-22275cd1700d.png">

**Desktop (please complete the following information):**
 - Browser: Firefox
 - Version: 74

 **Additional add-ons installed:**
Dark Reader, though it's turned off.

**Comment by Brettm12345** [comment]
Interesting... here is how it looks on my end. Make sure you don't have any other styles installed for github

![2020-04-03_07-44](https://user-images.githubusercontent.com/7571012/78357263-1dd4c080-757f-11ea-9638-6dee7d56ffc6.png)

**Comment by S3B4S** [comment]
Yeah I was already suspecting it was on my end. Did some debugging and it seems like the font colors are not getting loaded / overridden by the stylus theme, as the font colors are equivalent to those that I'd have if I toggle the theme off. So I'll start debugging there

**Comment by S3B4S** [comment]
Hmm it seems that in the local stylus file I don't have styles for `pl-smi`, `pl-k` and maybe some more. Even though I see they are in the source [source for pl-smi](https://github.com/Brettm12345/github-moonlight/blob/master/src/syntax.styl#L41), [source for pl-k](https://github.com/Brettm12345/github-moonlight/blob/master/src/syntax.styl#L43).

All of the `pl-X` related classes that appear in my local css file from stylus:
```
  .pl-c {
    color: var(--indigo) !important;
  }
  .pl-c1,
  .pl-s .pl-v {
    color: var(--text) !important;
  }
  .pl-e,
  .pl-en {
    color: var(--blue) !important;
  }
  .pl-s .pl-pse .pl-s1,
  .pl-pds {
    color: var(--cyan) !important;
  }
  .pl-s,
  .pl-sr .pl-sre,
  .pl-sr .pl-sra {
    color: var(--green) !important;
  }
  .pl-smw {
    color: var(--yellow) !important;
  }
  .pl-bu {
    color: var(--red) !important;
  }
  .pl-ii {
    color: var(--cn) !important;
    background-color: var(--red) !important;
  }
  .pl-c2 {
    color: var(--cn) !important;
    background-color: var(--red) !important;
  }
  .pl-c2::before {
    content: '^M';
  }
  .pl-sr .pl-cce {
    font-weight: bold !important;
  }
  .pl-ml {
    color: var(--orange) !important;
  }
  .pl-mh .pl-en,
  .pl-ms {
    color: var(--cyan) !important;
  }
  .pl-mh {
    color: var(--green) !important;
    font-weight: bold !important;
  }
  .pl-mi {
    color: var(--yellow) !important;
    font-style: italic;
  }
  .pl-mb {
    color: var(--cn) !important;
    font-weight: bold !important;
  }
  .pl-md {
    color: var(--red) !important;
    background-color: var(--red-trans) !important;
  }
  .pl-mi1 {
    color: var(--green) !important;
    background-color: var(--green-trans) !important;
  }
  .pl-mc {
    color: var(--purple) !important;
    background-color: var(--cyan-trans) !important;
  }
  .pl-mdr {
    color: var(--teal) !important;
    font-weight: bold !important;
  }
  .pl-ba {
    color: var(--hover) !important;
  }
  .pl-sg {
    color: var(--faded) !important;
  }
  .pl-corl {
    text-decoration: underline !important;
  }
```

**Comment by S3B4S** [comment]
There we go, I had to update 🙃
