### ISSUE TITLE
Unknown property 'scrollbar-color' and 'scrollbar-width'

### ISSUE THREAD

**Issue by aesophor** [Brettm12345/github-moonlight#32]
**Describe the bug:**
The scrollbar is not themed anymore. I navigated to the theme editing page in stylus and found these two issues:
![scrot-2020-04-04_095418_277x101](https://user-images.githubusercontent.com/32998585/78416380-f7845300-765a-11ea-93cb-07be84bdacb1.png)

**Expected behavior:**
Maybe the scrollbar is supposed to be themed like in previous versions?

**Where did this happen:**
Theme editing page (in stylus)

**Steps to reproduce:**
1. Install github-moonlight 2.10.10
2. Scrollbar is not themed
3. Navigate to theme editing page (in stylus) and these issues will be displayed.

**Screenshots:**
.

**Desktop (please complete the following information):**
 - OS: Linux (5.4.28-gentoo)
 - Browser: Firefox
 - Version: 74.0 (64-bit)

 **Additional add-ons installed:**
* Dark Reader (disabled on github)
* HTTPS Everywhere
* NoScript
* Privacy Badger
* uBlock Origin
* Video DownloadHelper
* Youtube Audio

**Comment by Brettm12345** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-color
