### ISSUE TITLE
Weird black 1px lines

### ISSUE THREAD

**Issue by Nuc1eoN** [Brettm12345/github-moonlight#34]
I have noticed there are several instances where the black 1px border seems to be out of place.
for example at the nav bar:
![image](https://user-images.githubusercontent.com/2538022/78464067-1f1ffd80-76e5-11ea-93d8-cf285dfeb98e.png)
(look bottom left and bottom right)

Then, in the header navbar text, while being in the dashboard:
![image](https://user-images.githubusercontent.com/2538022/78464081-52628c80-76e5-11ea-98ed-e99aeed12354.png)

In code formatted text:
![image](https://user-images.githubusercontent.com/2538022/78464092-7f16a400-76e5-11ea-8e74-38012593eb35.png)

And in the footer when in dashboard:
![image](https://user-images.githubusercontent.com/2538022/78464102-905fb080-76e5-11ea-93a2-42269ae6adcd.png)

**Comment by Brettm12345** [comment]
I think this has been fixed in the latest release

**Comment by Nuc1eoN** [comment]
Yes thanks, most of it is fixed! :)

There is still a line, above the 'Marketplace' button though:
![image](https://user-images.githubusercontent.com/2538022/79077222-2f953100-7d00-11ea-866e-f69d863a6a17.png)

Also, under a closed issue (like this one) there are two lines/separators at the bottom instead of one:
![image](https://user-images.githubusercontent.com/2538022/79077252-6d925500-7d00-11ea-9cd1-b3dc1084c429.png)


As a side note, I think it might actually be useful if the "closed issue button"  ![image](https://user-images.githubusercontent.com/2538022/79077295-e5607f80-7d00-11ea-89df-0dad9f2f651b.png) would also be colored red, just like in the original github theme^^

**Comment by Nuc1eoN** [comment]
@Brettm12345 
> There is still a line, above the 'Marketplace' button though:
> ![image](https://user-images.githubusercontent.com/2538022/79077222-2f953100-7d00-11ea-866e-f69d863a6a17.png)

Cannot reproduce this one anymore
> Also, under a closed issue (like this one) there are two lines/separators at the bottom instead of one:
> ![image](https://user-images.githubusercontent.com/2538022/79077252-6d925500-7d00-11ea-9cd1-b3dc1084c429.png)

This issue is still present (though, it happens only when nothing follows after the "closed" message)

> As a side note, I think it might actually be useful if the "closed issue button" ![image](https://user-images.githubusercontent.com/2538022/79077295-e5607f80-7d00-11ea-89df-0dad9f2f651b.png) would also be colored red, just like in the original github theme^^
> It could use the same color as the "Closed"-label: ![image](https://user-images.githubusercontent.com/2538022/79166039-a9064f80-7de4-11ea-86b9-73ba219aa019.png)

What about this suggestion? Do you think a red button would be valid, or is it supposed to be black?
For me it would probably make it pop-out more and make it more easily noticed by the eye.
