### ISSUE TITLE
White colors in the side bar (gitako)

### ISSUE THREAD

**Issue by AmrBinBashir** [Brettm12345/github-moonlight#37]
**Describe the bug:**
It's clear in the screenshot below, it only happened today, it was fine yesterday. Reinstalling doesn't help.

**Screenshots:**

![image](https://user-images.githubusercontent.com/48618675/78918662-0884f800-7a91-11ea-822a-fc097b8d28c2.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows 7] win10 v1909
 - Browser: [e.g. Chrome, Safari] Vivaldi 2.11  (chromium based)
 - Version: [e.g. 22] github-moonlight v1.2.0

 **Additional add-ons installed:**
A list of extensions you are using besides Stylus.
Dark Reader - (disabled for github)
Tampermonkey (no scripts for github)
github-vscode-icons
gitako

**Comment by gregk-git** [comment]
Can confirm, tested with:

| Operating System  | Browser |
| ------------- | ------------- |
| Windows 10 Build 18363 | Chrome Stable 80.0.3987.163 Official Build 64-bit |
| Windows 10 Build 18363 | Firefox Beta 75.0 (64-bit) |
| Ubuntu 18.04 | Firefox 75.0 64-bit |
| Ubuntu 18.04 | Chrome Beta 81.0.4044.92 (Official Build) beta (64-bit)

**Comment by shaansubbaiah** [comment]
@AmrBinBashir for now, you can try adding to the end of your file   
```
// fix Gitako
.search-input {
    border-color: var(--base-1) !important;
}

.gitako-side-bar .gitako-side-bar-body .gitako-side-bar-content .file-explorer .node-item,
.access-token-input,
.toggle-shortcut-input,
.search-input {
    background-color: var(--base-4) !important;
}
```

**Comment by AmrBinBashir** [comment]
@shaansubbaiah should i leave the issue open or close it ?

**Comment by AmrBinBashir** [comment]
@AmrBinBashir thanks, it's working fine now.

**Comment by Brettm12345** [comment]
@shaansubbaiah thank you for your solution. I will add it in shortly
