### ISSUE TITLE
Github reaction emoji, Comment makrdown editor in small screens have a white background

### ISSUE THREAD

**Issue by shaansubbaiah** [Brettm12345/github-moonlight#38]
**Describe the bug:**
Github reaction emoji, Comment makrdown editor in small screens have a white background

**Where did this happen:**
Any issue thread eg. https://github.com/Brettm12345/github-moonlight/issues/37

**Steps to reproduce:**
React with an emoji on a comment to see the white background.
Resize window to see the comment markdown toolbox use the white background.

**Screenshots:**

![image](https://user-images.githubusercontent.com/11163839/79036195-7d684700-7be3-11ea-9785-8673fd830ec0.png)

and 

![Peek 2020-04-11 11-02](https://user-images.githubusercontent.com/11163839/79036328-d4225080-7be4-11ea-9d2d-ec8b64acd61b.gif)

**Desktop (please complete the following information):**
 - OS: [Manjaro 19.02 (Linux, Arch based)]
 - Browser: [Firefox ]
 - Version: [75.0-1]

 **Additional add-ons installed:**
Gitako
UBlock Origin
 
**Fix for the emoji**
.reaction-summary-item.user-has-reacted {
    --background: var(--base-5) !important;
}

**Fix for the Toolbar**
.page-responsive .previewable-comment-form .comment-form-head.tabnav .toolbar-commenting {
    background: var(--base-3);
}

.border-md-top {
    border-top: 1px solid var(--base-1) !important;
}

![image](https://user-images.githubusercontent.com/11163839/79036499-65de8d80-7be6-11ea-921e-35034e0aa544.png)

**Comment by Brettm12345** [comment]
This seems to be fixed now
