### ISSUE TITLE
Font colors unreadable when authorizing applications

### ISSUE THREAD

**Issue by JorelAli** [Brettm12345/github-moonlight#7]
**Describe the bug**
The authorize application page on GitHub has unreadable text (in particular, Repositories and organization names)

**Expected behavior**
You can read it better (it should be in blue text with that dark blue background)

**Screenshots**
![image](https://user-images.githubusercontent.com/4613171/78110091-56935f00-73f2-11ea-8f21-cb286626f99d.png)

**Desktop (please complete the following information):**
 - OS: NixOS
 - Browser: Brave
 - Version: 77.0.69.128

**Comment by Brettm12345** [comment]
I can't seem to re-create this dialog for myself. Would you share the css class of the thing with the white background and I'll change it. Thank you

**Comment by JorelAli** [comment]
- For the thing with the white background: `.oauth-org-access-details .oauth-org-item:first-child`
- For the word "Repositories": `.oauth-permissions-details .permission-title`
- For the words public and private: `.oauth-repo-permissions.default .default-access, .oauth-repo-permissions.full .full-access, .oauth-repo-permissions.limited-repo-invite .limited-repo-invite-access, .oauth-repo-permissions.public .public-access`
- For the word private (which is highlighted): `.oauth-permissions-details .permission-summary em.highlight`
